### Makefile -- Docker Garbage Collector

# Docker Toolkit (https://github.com/michipili/dockertk)
# This file is part of Docker Toolkit
#
# Copyright © 2015 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

PROGRAM=		docker_gc

SRCS=			dockerGc_Configuration.ml
SRCS+=			dockerGc_Policy.ml
SRCS+=			dockerGc_Container.ml
SRCS+=			dockerGc_Image.ml
SRCS+=			dockerGc_Main.ml

.include "ocaml.prog.mk"
